#_*_ coding: shift-jis _*_
# author:bartomo

#: import main exam_kivy

#TextWidget:
#ImageWidget:
<MyButton@Button>
    font_size: 48


#<TextWidget>:
#    BoxLayout:
#        orientation: "vertical"
#        size: root.size
#
#        Label:
#            id:label1
#            font_size: 68
#            text: root.text
#
#        BoxLayout:
#            orientation: "horizontal"
#
#
#            TextInput:
#                id: text_box
#                size_hint_x: 70
#                font_size: 68
#                on_text_validate: root.buttonClickedText()
#
#            Button:
#                id: button1
#                size_hint_x: 30
#                text: "OK"
#                font_size: 68
#                on_press: main.buttonClickedText()


<MusicPlayer>
    status: status_text
    play_button: play_button
    stop_button: stop_button
    time_bar: time_bar
    time_text: time_text
    volume_bar: volume_bar
    volume_text: volume_text
    exam_number: exam_number

    orientation: 'vertical'
    padding: 20

    Label:
        size_hint: 1, .1
        id: exam_number
        text: "Show exam_number"
        center: root.center
        color: 1, 0, 0, 1

    Label:
        size_hint: 1, .5
        id: status_text
        text: ""
        center: root.center
        color: 1, 0, 0, 1

    BoxLayout:
        size_hint: 1, .1

        Label:
            id: time_text
            size_hint: 0.1, 1
            text: '0:00/0:00'

        Slider:
            id: time_bar
            size_hint: 0.9, 1
            max: 100
            value: 0
            on_value :root.time_change(self.value)


    BoxLayout:
        size_hint:1, .1
        Button:
            id: play_button
            text: 'Interval'
            background_color: 0, .5, 1, 1
            on_release: root.play_or_stop()

        Button:
            id: stop_button
            text: 'Stop'
            background_color: 0, .5, 1, 1
            on_release: root.stop()

        Label:
            id: volume_text
            text: '50'

        Slider:
            id: volume_bar
            max: 100
            value: 50
            on_value: root.volume_change(self.value)

        Button:
            text: 'Choose File'
            on_release: root.choose()


    BoxLayout:
        size_hint: 1, .1

        Label:
            id: config_set
            text: '出題設定'
        TextInput:

        Label:
            id: exam_number
            text: '問題数'
        TextInput:

        Label:
            id: terms_exam_number
            text: '項数'
        TextInput:


    BoxLayout:
        size_hint: 1, .3
        Button:
            id: exam_create
            text: '問題生成'
            background_color: 0, .5, 1, 1
            on_release: root._create_number_list()

        Button:
            id: class_setting
            text: '級変更'




<PopupChooseFile>
    canvas:
        Color:
            rgba: 0, 0, .4, 1
        Rectangle:
            pos: self.pos
            size: self.size

    orientation: "vertical"

    FileChooserIconView:
        size_hint: 1, .9
        path: root.current_dir
        on_submit: root.select(self.selection[0])
    BoxLayout:
        size_hint: 1, .1
        Button:
            text: "Cancel"
            background_color: 0, .5, 1, 1
            on_release: root.cancel()